Do not assign to the slice object
Slices are read-only, so this commit solves the following problem:

>>> s = slice(2, 10)
>>> l = list("abcdefghijlmn")
>>> nltk.slice_bounds(l, s, allow_step=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peter/Projekt/NLTK/nltk/nltk/internals.py", line 781, in slice_bounds
    if slice_obj.step is None: slice_obj.step = 1
TypeError: readonly attribute