numpy shouldn't be required to import nltk
'import nltk' fails without this when numpy is absent:

>>> import nltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/__init__.py", line 102, in <module>
    from .collocations import *
  File "nltk/collocations.py", line 39, in <module>
    from nltk.metrics import ContingencyMeasures, BigramAssocMeasures, TrigramAssocMeasures
  File "nltk/metrics/__init__.py", line 23, in <module>
    from nltk.metrics.segmentation    import windowdiff, ghd, pk
  File "nltk/metrics/segmentation.py", line 44, in <module>
    import numpy as np
ImportError: No module named numpy